# Home: https://www.jetbrains.com/pycharm/download/?section=linux

- name: Create directory
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop:
    - "{{ to }}"
    - "{{ cache }}"

- name: Download PyCharm
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ cache }}/{{ file_name }}"
    # checksum: "sha256:{{ checksum_url }}"

- name: Extract PyCharm
  ansible.builtin.unarchive:
    src: "{{ cache }}/{{ file_name }}"
    dest: "{{ to }}/"
    creates: "{{ to }}/pycharm-community-{{ version }}"
    remote_src: yes

- name: Launcher - Desktop file
  ansible.builtin.template:
    src: jetbrains-pycharm-ce.desktop.j2
    dest: "/home/{{ ansible_env.USER }}/.local/share/applications/jetbrains-pycharm-ce.desktop"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0664'
  become: true