---
# Install packer from Official repo
# https://developer.hashicorp.com/packer/downloads

- name: prerequisite
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: latest

# Will NOT work with yum_repository! https://github.com/ansible/ansible/issues/46963
- name: Add repository manually, alt
  become: true
  ansible.builtin.command: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

- name: Install Packer
  become: true
  ansible.builtin.dnf:
    name:
      - packer
    state: latest
